const storeKey='monUniversV1';
const defaultData={events:[{title:'Préparer ma semaine',date:new Date().toISOString().slice(0,10),time:'09:00',type:'Perso'},{title:'Point pro',date:new Date().toISOString().slice(0,10),time:'15:00',type:'Pro'}],tasks:[{text:'Faire le point budget du mois',category:'Perso',done:false},{text:'Noter mes priorités pro',category:'Pro',done:false}],notes:[{title:'Idée',category:'Perso',body:'Créer une routine douce du matin.'}],budget:[{label:'Salaire',amount:2400,type:'income'},{label:'Courses',amount:250,type:'expense'}],shopping:['Café','Légumes','Lessive'],cleaning:['Cuisine','Salle de bain','Aspirateur','Lessive'],icsLink:''};
let data=JSON.parse(localStorage.getItem(storeKey)||'null')||defaultData;
const messages=['Aujourd’hui, avance doucement. Même un petit pas compte.','Tu n’as pas besoin de tout porter seule. Respire, puis choisis une chose.','Ton énergie est précieuse : protège-la avec douceur.','Ce qui est fait avec le cœur finit toujours par trouver sa place.','Tu as le droit de recommencer autant de fois que nécessaire.'];
function save(){localStorage.setItem(storeKey,JSON.stringify(data));render()}
function euro(n){return new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format(n)}
function render(){document.getElementById('todayLabel').textContent=new Date().toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long'});if(!document.getElementById('universeMessage').textContent)document.getElementById('universeMessage').textContent=messages[new Date().getDate()%messages.length];const today=new Date().toISOString().slice(0,10);let todayEvents=data.events.filter(e=>e.date===today);document.getElementById('todayEventsCount').textContent=todayEvents.length;document.getElementById('openTasksCount').textContent=data.tasks.filter(t=>!t.done).length;let total=data.budget.reduce((s,b)=>s+(b.type==='income'?+b.amount:-b.amount),0);document.getElementById('budgetLeft').textContent=euro(total);document.getElementById('personalSummary').innerHTML=summary('Perso');document.getElementById('proSummary').innerHTML=summary('Pro');listEvents();listTasks();listNotes();listBudget();listShopping();listCleaning();document.getElementById('icsLink').value=data.icsLink||''}
function summary(cat){let ev=data.events.filter(e=>e.type===cat).slice(0,3).map(e=>`<div class="item"><span>${e.date} ${e.time||''} — ${e.title}</span><span class="pill">${cat}</span></div>`).join('');let tasks=data.tasks.filter(t=>t.category===cat&&!t.done).slice(0,2).map(t=>`<div class="item"><span>${t.text}</span><span class="pill">à faire</span></div>`).join('');return ev+tasks||'<p class="eyebrow">Rien de prévu pour le moment.</p>'}
function listEvents(){eventsList.innerHTML=data.events.sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).map((e,i)=>`<div class="item"><div><strong>${e.title}</strong><br><small>${e.date} ${e.time||''}</small></div><span class="pill">${e.type}</span><button class="delete" onclick="data.events.splice(${i},1);save()">×</button></div>`).join('')}
function listTasks(){tasksList.innerHTML=data.tasks.map((t,i)=>`<div class="item"><label class="${t.done?'done':''}"><input type="checkbox" ${t.done?'checked':''} onchange="data.tasks[${i}].done=this.checked;save()"> ${t.text}</label><span class="pill">${t.category}</span><button class="delete" onclick="data.tasks.splice(${i},1);save()">×</button></div>`).join('')}
function listNotes(){notesList.innerHTML=data.notes.map((n,i)=>`<div class="card"><div class="item"><strong>${n.title}</strong><span class="pill">${n.category}</span><button class="delete" onclick="data.notes.splice(${i},1);save()">×</button></div><p>${n.body}</p></div>`).join('')}
function listBudget(){budgetList.innerHTML=data.budget.map((b,i)=>`<div class="item"><span>${b.label}</span><strong>${b.type==='income'?'+':'-'} ${euro(b.amount)}</strong><button class="delete" onclick="data.budget.splice(${i},1);save()">×</button></div>`).join('')}
function listShopping(){shoppingList.innerHTML=data.shopping.map((s,i)=>`<div class="item"><label><input type="checkbox"> ${s}</label><button class="delete" onclick="data.shopping.splice(${i},1);save()">×</button></div>`).join('')}
function listCleaning(){cleaningList.innerHTML=data.cleaning.map((s,i)=>`<div class="item"><label><input type="checkbox"> ${s}</label></div>`).join('')}
document.querySelectorAll('.nav-btn').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.nav-btn,.view').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.getElementById(btn.dataset.view).classList.add('active')});
newMessage.onclick=()=>universeMessage.textContent=messages[Math.floor(Math.random()*messages.length)];
resetDemo.onclick=()=>{if(confirm('Réinitialiser les données ?')){data=defaultData;save()}};
eventForm.onsubmit=e=>{e.preventDefault();data.events.push(Object.fromEntries(new FormData(e.target)));e.target.reset();save()};
taskForm.onsubmit=e=>{e.preventDefault();data.tasks.push({...Object.fromEntries(new FormData(e.target)),done:false});e.target.reset();save()};
noteForm.onsubmit=e=>{e.preventDefault();data.notes.unshift(Object.fromEntries(new FormData(e.target)));e.target.reset();save()};
budgetForm.onsubmit=e=>{e.preventDefault();let o=Object.fromEntries(new FormData(e.target));o.amount=Number(o.amount);data.budget.push(o);e.target.reset();save()};
shoppingForm.onsubmit=e=>{e.preventDefault();data.shopping.push(new FormData(e.target).get('item'));e.target.reset();save()};
icsLink.onchange=e=>{data.icsLink=e.target.value;save()};
render();
