const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const todayISO=()=>new Date().toISOString().slice(0,10);
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
const money=n=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format(Number(n||0));
const store={get(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}},set(k,v){localStorage.setItem(k,JSON.stringify(v))}};
const defaults={events:[{id:uid(),title:'Service déjeuner',date:todayISO(),time:'11:00',category:'pro',reminder:30},{id:uid(),title:'Réunion d’équipe',date:todayISO(),time:'14:30',category:'pro',reminder:15},{id:uid(),title:'Service dîner',date:todayISO(),time:'18:30',category:'pro',reminder:30}],tasks:[{id:uid(),title:'Préparer événement',category:'pro',due:todayISO(),priority:true,done:false},{id:uid(),title:'Suivi budget',category:'perso',due:todayISO(),priority:true,done:false},{id:uid(),title:'Sport 30 min',category:'perso',due:todayISO(),priority:false,done:false}],notes:[],expenses:[{id:uid(),label:'Courses',amount:82.4,category:'Courses',date:todayISO()}],shopping:[{id:uid(),title:'Lait',category:'Frais',done:false},{id:uid(),title:'Fruits',category:'Fruits & légumes',done:false}],routine:[['Cuisine',false],['Aspirateur',false],['Salle de bain',false],['Lessive',false],['Papiers',false]],settings:{displayName:'Betty',dailyTime:'08:00',budgetThreshold:200,budgetLimit:1200},readNotifications:[]};
let state={events:store.get('mu_events',defaults.events),tasks:store.get('mu_tasks',defaults.tasks),notes:store.get('mu_notes',defaults.notes),expenses:store.get('mu_expenses',defaults.expenses),shopping:store.get('mu_shopping',defaults.shopping),routine:store.get('mu_routine',defaults.routine),settings:store.get('mu_settings',defaults.settings),readNotifications:store.get('mu_read',[])};
const messages=['Tu es exactement là où tu dois être. Fais confiance au processus.','Aujourd’hui, choisis la paix plutôt que la pression.','Ce que tu construis doucement peut durer longtemps.','Tu n’as pas besoin de tout réussir aujourd’hui, seulement d’avancer.','Ton intuition connaît déjà le chemin.'];
const inspirations=['Discipline aujourd’hui, liberté demain.','Ta douceur est aussi une force.','Les petits pas créent les grands changements.','Protège ton énergie, elle est précieuse.','Tu peux recommencer autant de fois que nécessaire.'];
let eventFilter='all',taskFilter='all';
function persist(){store.set('mu_events',state.events);store.set('mu_tasks',state.tasks);store.set('mu_notes',state.notes);store.set('mu_expenses',state.expenses);store.set('mu_shopping',state.shopping);store.set('mu_routine',state.routine);store.set('mu_settings',state.settings);store.set('mu_read',state.readNotifications)}
function showToast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
function setPage(id){$$('.page').forEach(p=>p.classList.toggle('active',p.id===id));$$('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===id));$('#sidePanel').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'});renderAll()}
$$('[data-page]').forEach(b=>b.onclick=()=>setPage(b.dataset.page));$$('[data-go]').forEach(b=>b.onclick=()=>setPage(b.dataset.go));$('#menuBtn').onclick=()=>$('#sidePanel').classList.toggle('open');
function openModal(id){$$('.modal').forEach(m=>m.classList.remove('open'));$('#'+id)?.classList.add('open')}
function closeModals(){$$('.modal').forEach(m=>m.classList.remove('open'))}
$$('[data-open-modal]').forEach(b=>b.onclick=()=>openModal(b.dataset.openModal));$$('[data-close-modal]').forEach(b=>b.onclick=closeModals);$('#quickAddBtn').onclick=()=>openModal('quickAddModal');
function dateLong(d){return new Date(d+'T12:00:00').toLocaleDateString('fr-FR',{weekday:'short',day:'numeric',month:'long'})}
function renderHome(){const d=new Date();$('#todayDate').textContent=d.toLocaleDateString('fr-FR',{day:'numeric',month:'long',year:'numeric'}).toUpperCase();const dailyIndex=Number(localStorage.getItem('mu_message_index')||d.getDate())%messages.length;$('#dailyMessage').innerHTML=messages[dailyIndex].replace('. ','.<br>');$('#inspirationText').textContent=inspirations[d.getDate()%inspirations.length];$('#sideMessage').textContent=messages[(dailyIndex+1)%messages.length];const events=state.events.filter(e=>e.date===todayISO()).sort((a,b)=>a.time.localeCompare(b.time));$('#homeAgenda').innerHTML=events.length?events.slice(0,4).map(e=>`<div><b>${e.time}</b><span>${escapeHtml(e.title)}</span></div>`).join(''):'<span class="empty">Aucun rendez-vous aujourd’hui.</span>';const priorities=state.tasks.filter(t=>!t.done).sort((a,b)=>b.priority-a.priority).slice(0,4);$('#homePriorities').innerHTML=priorities.length?priorities.map(t=>`<label><input type="checkbox" data-home-task="${t.id}"> ${escapeHtml(t.title)}</label>`).join(''):'<p class="subtitle">Tout est à jour ✨</p>';$$('[data-home-task]').forEach(c=>c.onchange=()=>toggleTask(c.dataset.homeTask));['pro','perso'].forEach(cat=>{const arr=state.tasks.filter(t=>t.category===cat),done=arr.filter(t=>t.done).length,p=arr.length?Math.round(done/arr.length*100):0;const ring=$('#'+(cat==='pro'?'proRing':'personalRing'));ring.style.setProperty('--p',p);ring.dataset.label=p+'%';$('#'+(cat==='pro'?'proProgress':'personalProgress')).innerHTML=arr.length?`Objectifs de la semaine<br>${done}/${arr.length} terminés`:'Aucune tâche';});renderBudgetSummary()}
$('#newMessageBtn').onclick=()=>{const i=(Number(localStorage.getItem('mu_message_index')||0)+1)%messages.length;localStorage.setItem('mu_message_index',i);$('#dailyMessage').innerHTML=messages[i].replace('. ','.<br>');showToast('Nouveau message ✨')};$('#momentBtn').onclick=()=>openModal('todayModal');
function renderEvents(){const arr=state.events.filter(e=>eventFilter==='all'||e.category===eventFilter).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));$('#eventList').innerHTML=arr.length?arr.map(e=>`<article class="list-card"><div class="badge ${e.category}">${e.category}</div><div class="main"><strong>${escapeHtml(e.title)}</strong><small>${dateLong(e.date)} · ${e.time} · rappel ${e.reminder} min</small></div><button class="delete-btn" data-del-event="${e.id}">×</button></article>`).join(''):'<p class="subtitle">Aucun rendez-vous.</p>';$$('[data-del-event]').forEach(b=>b.onclick=()=>{state.events=state.events.filter(e=>e.id!==b.dataset.delEvent);persist();renderAll()})}
$$('[data-event-filter]').forEach(b=>b.onclick=()=>{eventFilter=b.dataset.eventFilter;$$('[data-event-filter]').forEach(x=>x.classList.toggle('active',x===b));renderEvents()});
$('#eventForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);state.events.push({id:uid(),title:f.get('title'),date:f.get('date'),time:f.get('time'),category:f.get('category'),reminder:Number(f.get('reminder'))});persist();e.target.reset();closeModals();renderAll();showToast('Rendez-vous ajouté')};
function renderTasks(){let arr=state.tasks.filter(t=>taskFilter==='all'||(taskFilter==='pending'?!t.done:t.category===taskFilter));arr.sort((a,b)=>Number(b.priority)-Number(a.priority));$('#taskList').innerHTML=arr.length?arr.map(t=>`<article class="list-card ${t.done?'done':''}"><input class="check-toggle" type="checkbox" ${t.done?'checked':''} data-task-toggle="${t.id}"><div class="main"><strong>${t.priority?'★ ':''}${escapeHtml(t.title)}</strong><small>${t.category==='pro'?'Professionnel':'Personnel'}${t.due?' · '+dateLong(t.due):''}</small></div><button class="delete-btn" data-del-task="${t.id}">×</button></article>`).join(''):'<p class="subtitle">Aucune tâche.</p>';$$('[data-task-toggle]').forEach(c=>c.onchange=()=>toggleTask(c.dataset.taskToggle));$$('[data-del-task]').forEach(b=>b.onclick=()=>{state.tasks=state.tasks.filter(t=>t.id!==b.dataset.delTask);persist();renderAll()})}
function toggleTask(id){const t=state.tasks.find(x=>x.id===id);if(t)t.done=!t.done;persist();renderAll()}
$$('[data-task-filter]').forEach(b=>b.onclick=()=>{taskFilter=b.dataset.taskFilter;$$('[data-task-filter]').forEach(x=>x.classList.toggle('active',x===b));renderTasks()});
$('#taskForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);state.tasks.push({id:uid(),title:f.get('title'),category:f.get('category'),due:f.get('due'),priority:f.get('priority')==='on',done:false});persist();e.target.reset();closeModals();renderAll();showToast('Tâche ajoutée')};
function renderNotes(){$('#savedNotes').innerHTML=state.notes.length?state.notes.slice().reverse().map(n=>`<article class="note-card"><span class="badge ${n.category}">${n.category}</span><h3>${escapeHtml(n.title||'Ma note')}</h3><p>${escapeHtml(n.content)}</p><button class="delete-btn" data-del-note="${n.id}">Supprimer</button></article>`).join(''):'<p class="subtitle">Aucune note enregistrée.</p>';$$('[data-del-note]').forEach(b=>b.onclick=()=>{state.notes=state.notes.filter(n=>n.id!==b.dataset.delNote);persist();renderNotes()})}
$('#noteForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);state.notes.push({id:uid(),title:f.get('title'),category:f.get('category'),content:f.get('content'),date:todayISO()});persist();e.target.reset();closeModals();renderAll();showToast('Note enregistrée')};
function budgetData(){const spent=state.expenses.reduce((s,e)=>s+Number(e.amount),0),limit=Number(state.settings.budgetLimit||0);return{spent,limit,remaining:limit-spent,pct:limit?Math.min(100,spent/limit*100):0}}
function renderBudgetSummary(){const b=budgetData();$('#homeBudgetRemaining').textContent=money(b.remaining);$('#homeBudgetTotal').textContent='sur '+money(b.limit);$('#homeBudgetBar').style.width=b.pct+'%';$('#budgetLimitLabel').textContent=money(b.limit);$('#spentLabel').textContent=money(b.spent);$('#remainingLabel').textContent=money(b.remaining);$('#budgetProgress').style.width=b.pct+'%'}
function renderExpenses(){renderBudgetSummary();$('#expenseList').innerHTML=state.expenses.length?state.expenses.slice().reverse().map(x=>`<article class="list-card"><div class="badge">${escapeHtml(x.category)}</div><div class="main"><strong>${escapeHtml(x.label)}</strong><small>${dateLong(x.date)}</small></div><strong>${money(x.amount)}</strong><button class="delete-btn" data-del-expense="${x.id}">×</button></article>`).join(''):'<p class="subtitle">Aucune dépense.</p>';$$('[data-del-expense]').forEach(b=>b.onclick=()=>{state.expenses=state.expenses.filter(x=>x.id!==b.dataset.delExpense);persist();renderAll()})}
$('#expenseForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);state.expenses.push({id:uid(),label:f.get('label'),amount:Number(f.get('amount')),category:f.get('category'),date:todayISO()});persist();e.target.reset();closeModals();renderAll();showToast('Dépense ajoutée')};$('#editBudgetBtn').onclick=()=>{const v=prompt('Quel est ton budget mensuel ?',state.settings.budgetLimit);if(v!==null&&!isNaN(v)){state.settings.budgetLimit=Number(v);persist();renderAll()}};
function renderShopping(){$('#shoppingList').innerHTML=state.shopping.length?state.shopping.map(x=>`<article class="list-card ${x.done?'done':''}"><input class="check-toggle" type="checkbox" ${x.done?'checked':''} data-shop-toggle="${x.id}"><div class="badge">${escapeHtml(x.category)}</div><div class="main"><strong>${escapeHtml(x.title)}</strong></div><button class="delete-btn" data-del-shop="${x.id}">×</button></article>`).join(''):'<p class="subtitle">La liste est vide.</p>';$$('[data-shop-toggle]').forEach(c=>c.onchange=()=>{const x=state.shopping.find(i=>i.id===c.dataset.shopToggle);x.done=!x.done;persist();renderAll()});$$('[data-del-shop]').forEach(b=>b.onclick=()=>{state.shopping=state.shopping.filter(x=>x.id!==b.dataset.delShop);persist();renderAll()})}
$('#shoppingForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);state.shopping.push({id:uid(),title:f.get('title'),category:f.get('category'),done:false});persist();e.target.reset();closeModals();renderAll();showToast('Ajouté aux courses')};
function renderRoutine(){$('#routineList').innerHTML=state.routine.map((r,i)=>`<label class="routine-item ${r[1]?'done':''}"><input type="checkbox" ${r[1]?'checked':''} data-routine="${i}"><span>${escapeHtml(r[0])}</span></label>`).join('');$$('[data-routine]').forEach(c=>c.onchange=()=>{state.routine[Number(c.dataset.routine)][1]=c.checked;persist();renderRoutine()})}$('#resetRoutineBtn').onclick=()=>{state.routine=state.routine.map(x=>[x[0],false]);persist();renderRoutine();showToast('Routine réinitialisée')};
function notifications(){const now=new Date(),items=[];state.events.forEach(e=>{const dt=new Date(`${e.date}T${e.time}:00`),diff=(dt-now)/60000;if(diff>=0&&diff<=1440)items.push({id:'event-'+e.id,type:'Agenda',title:e.title,detail:diff<60?`Dans ${Math.max(1,Math.round(diff))} min`:`Aujourd’hui à ${e.time}`,page:'agenda'})});state.tasks.filter(t=>!t.done&&(t.due===todayISO()||t.priority)).slice(0,4).forEach(t=>items.push({id:'task-'+t.id,type:'Tâche',title:t.title,detail:t.category==='pro'?'Priorité professionnelle':'À faire aujourd’hui',page:'tasks'}));const b=budgetData();if(b.remaining<=Number(state.settings.budgetThreshold))items.push({id:'budget-alert',type:'Budget',title:`Il te reste ${money(b.remaining)}`,detail:'Tu approches de ton seuil d’alerte.',page:'budget'});const unbought=state.shopping.filter(x=>!x.done).length;if(unbought)items.push({id:'shopping-alert',type:'Courses',title:`${unbought} article${unbought>1?'s':''} à acheter`,detail:'Ta liste de courses t’attend.',page:'shopping'});items.push({id:'daily-'+todayISO(),type:'Univers',title:messages[new Date().getDate()%messages.length],detail:'Ton message du jour',page:'home'});return items}
function renderNotifications(){const items=notifications(),unread=items.filter(n=>!state.readNotifications.includes(n.id));const count=$('#notificationCount');count.textContent=unread.length;count.dataset.count=unread.length;$('#notificationSummary').textContent=`${unread.length} nouvelle${unread.length>1?'s':''} alerte${unread.length>1?'s':''}`;$('#notificationList').innerHTML=items.map(n=>`<article class="notification-item ${state.readNotifications.includes(n.id)?'':'unread'}" data-notif="${n.id}" data-target="${n.page}"><span class="badge">${n.type}</span><strong>${escapeHtml(n.title)}</strong><small>${escapeHtml(n.detail)}</small></article>`).join('');$$('[data-notif]').forEach(n=>n.onclick=()=>{if(!state.readNotifications.includes(n.dataset.notif))state.readNotifications.push(n.dataset.notif);persist();closeNotifications();setPage(n.dataset.target)})}
function openNotifications(){$('#notificationOverlay').classList.add('open');$('#notificationOverlay').setAttribute('aria-hidden','false');renderNotifications()}function closeNotifications(){$('#notificationOverlay').classList.remove('open');$('#notificationOverlay').setAttribute('aria-hidden','true')}$('#notificationBtn').onclick=openNotifications;$$('[data-close-notifications]').forEach(b=>b.onclick=closeNotifications);$('#markAllRead').onclick=()=>{state.readNotifications=[...new Set([...state.readNotifications,...notifications().map(n=>n.id)])];persist();renderNotifications()};
function renderTodayBrief(){const ev=state.events.filter(e=>e.date===todayISO()),tasks=state.tasks.filter(t=>!t.done&&(t.due===todayISO()||t.priority)),b=budgetData(),shop=state.shopping.filter(x=>!x.done).length;$('#todayBriefContent').innerHTML=`<div class="brief-list"><div>📅 ${ev.length} rendez-vous aujourd’hui</div><div>✓ ${tasks.length} tâche${tasks.length>1?'s':''} à faire</div><div>💰 Il te reste ${money(b.remaining)}</div><div>🛒 ${shop} article${shop>1?'s':''} sur ta liste</div><div>✨ ${messages[new Date().getDate()%messages.length]}</div></div>`}$('#todayBriefBtn').onclick=()=>{renderTodayBrief();openModal('todayModal')};
function renderSettings(){$('#displayName').value=state.settings.displayName;$('#dailyTime').value=state.settings.dailyTime;$('#budgetThreshold').value=state.settings.budgetThreshold}$('#saveSettingsBtn').onclick=()=>{state.settings.displayName=$('#displayName').value||'Betty';state.settings.dailyTime=$('#dailyTime').value;state.settings.budgetThreshold=Number($('#budgetThreshold').value||0);persist();showToast('Réglages enregistrés');renderAll()};$('#installHelpBtn').onclick=()=>alert('Sur iPhone : ouvre le lien dans Safari, touche Partager, puis « Ajouter à l’écran d’accueil ».\n\nSur Android : ouvre le menu du navigateur puis « Installer l’application ».');
function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function renderAll(){renderHome();renderEvents();renderTasks();renderNotes();renderExpenses();renderShopping();renderRoutine();renderSettings();renderNotifications()}
renderAll();
